import streamlit as st

def launch_ui():
    st.set_page_config(page_title="SignSafe", layout="centered")
    st.title("📜 SignSafe")
    st.markdown("**Understand any legal document – even if you can't read legal language.**")

    st.header("📂 Upload a Document")
    uploaded_file = st.file_uploader("Choose a PDF or image", type=["pdf", "png", "jpg", "jpeg", "docx"])

    if uploaded_file:
        st.success("✅ File uploaded successfully!")
        st.subheader("🧠 Here's what we found:")
        st.markdown("---")

        # Sample clause data – will be replaced by real backend later
        sample_clauses = [
            {
                "original": "The lessee shall indemnify the lessor for any damages...",
                "simple": "If anything gets damaged while you're living there, you have to pay for it.",
                "risk": "high"
            },
            {
                "original": "This agreement shall renew automatically unless terminated...",
                "simple": "It will auto-renew unless you cancel it yourself.",
                "risk": "medium"
            },
            {
                "original": "This contract is governed by the laws of another state...",
                "simple": "If there’s a problem, it’ll be settled in a different state’s court.",
                "risk": "medium"
            }
        ]

        for i, clause in enumerate(sample_clauses, start=1):
            st.markdown(f"### 📜 Clause {i}")
            st.markdown(f"**Original:** {clause['original']}")
            st.markdown(f"**In Simple Words:** {clause['simple']}")

            if clause["risk"] == "high":
                st.error("🔴 High Risk")
            elif clause["risk"] == "medium":
                st.warning("🟡 Medium Risk")
            else:
                st.success("🟢 Low Risk")

            # Audio removed until generated by backend
            # st.audio(...)

            st.markdown("---")

    # Footer
    st.markdown("---")
    st.caption("🔒 SignSafe is built for Microsoft Code Cubicle 4.0 • Team LegalSage")
